services:
  db:
    image: bitnami/postgresql:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=clube_feijao_db
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - backend

  api:
    image: node:20-slim
    container_name: clube-feijao-api
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clube_feijao_db?schema=public
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:


networks:
  backend:
 